"""empty message

Revision ID: 01081b303b1e
Revises: 
Create Date: 2022-07-25 22:42:38.001712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01081b303b1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'url')
    # ### end Alembic commands ###
