"""empty message

Revision ID: 2fa6a37553bb
Revises: 01081b303b1e
Create Date: 2022-07-25 23:54:56.842129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa6a37553bb'
down_revision = '01081b303b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('url', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
